double * creerMatrice(int n);
void detruireMatrice(double * A);
void afficherMatrice(int n, double * A);
double * somme2Matrices(int n, double * A, double * B);
double * produitReelMatrice(int n, double r, double * A);
double * produit2Matrices(int n, double * A, double * B);
double * copieMatrice(int n, double * A);
double * transposeeMatrice(int n, double * A);
double * matriceSansLC(int n, double * A, int L, int C);
double determinant(int taille, double* A);
double * comatrice(int n, double * A);
double * inverserMatrice(int n, double * A);
